# Generated by Django 6.0.2 on 2026-03-02 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organizations', '0002_alter_department_options_department_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Jadval nomi')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('date_from', models.DateField(verbose_name='Boshlanish sanasi')),
                ('date_to', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': 'Jadvallar',
                'db_table': 'schedules',
                'unique_together': {('organization', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Nazariy'), ('practice', 'Amaliy')], max_length=20)),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('is_substituted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.building', verbose_name='Bino')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='academic.group')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.para')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.room', verbose_name='Xona')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Jadval elementi',
                'verbose_name_plural': 'Jadval elementlari',
                'db_table': 'schedule_entries',
                'ordering': ['date', 'para__order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organizations.organization')),
                ('personal_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.room', verbose_name='Shaxsiy xona')),
                ('subjects', models.ManyToManyField(blank=True, to='academic.subject', verbose_name="O'qita oladigan fanlar")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('status', models.CharField(choices=[('requested', "So'ralgan"), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='scheduling.scheduleentry')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_substitutions', to='scheduling.teacher')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_substitutions', to='scheduling.teacher')),
            ],
            options={
                'verbose_name': "O'rinbosarlik",
                'verbose_name_plural': "O'rinbosarliklar",
                'db_table': 'substitutions',
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherBusyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Sabab')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_times', to='scheduling.teacher')),
            ],
            options={
                'verbose_name': 'Band vaqt',
                'verbose_name_plural': 'Band vaqtlar',
                'db_table': 'teacher_busy_times',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Tahrirlandi'), ('delete', "O'chirildi"), ('generate', 'Generatsiya'), ('publish', 'Nashr etildi'), ('approve', 'Tasdiqlandi'), ('reject', 'Rad etildi'), ('substitute', "O'rinbosar")], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit logi',
                'verbose_name_plural': 'Audit loglari',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='audit_logs_organiz_9c8c67_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherMonthlyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('total_hours', models.PositiveSmallIntegerField(verbose_name='Oylik soat')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_loads', to='academic.major')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_loads', to='scheduling.teacher')),
            ],
            options={
                'verbose_name': 'Oylik yukla',
                'verbose_name_plural': 'Oylik yuklamalar',
                'db_table': 'teacher_monthly_loads',
                'unique_together': {('teacher', 'major', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.major')),
                ('subjects', models.ManyToManyField(related_name='teacher_assignments', to='academic.subject', verbose_name='Fanlar')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='scheduling.teacher')),
            ],
            options={
                'verbose_name': "O'qituvchi fan biriktiruvi",
                'verbose_name_plural': "O'qituvchi fan biriktiruvilari",
                'db_table': 'teacher_subject_assignments',
                'unique_together': {('teacher', 'major')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.curriculumsubject')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academic.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='scheduling.teacher')),
            ],
            options={
                'verbose_name': "O'qituvchi biriktiruvi",
                'verbose_name_plural': "O'qituvchi biriktiruvilari",
                'db_table': 'teaching_assignments',
                'unique_together': {('teacher', 'group', 'curriculum_subject')},
            },
        ),
    ]
