# Generated by Django 6.0.2 on 2026-03-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
