# Generated by Django 6.0.2 on 2026-04-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_curriculumsubject_options_and_more'),
        ('organizations', '0002_alter_department_options_department_manager'),
        ('scheduling', '0002_delete_teachingassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_sheets', to='organizations.department', verbose_name='Kafedra')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_load_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': "Taqsimot varag'i",
                'verbose_name_plural': 'Taqsimot varaqlari',
                'db_table': 'load_sheets',
                'ordering': ['-year', '-month'],
                'unique_together': {('department', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Teacher topilmasa ham Excel dagi ism saqlanadi', max_length=255, verbose_name='F.I.Sh (Excel dan)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Lavozim')),
                ('stavka', models.CharField(choices=[('1.0', "To'liq stavka (1.0)"), ('0.5', 'Yarim stavka (0.5)'), ('0.25', 'Chorak stavka (0.25)'), ('soatbay', 'Soatbay'), ('vokant', "Vokant (bo'sh o'rin)")], default='1.0', max_length=20, verbose_name='Stavka')),
                ('total_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Jami soat (Hammasi)')),
                ('load_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_loads', to='scheduling.loadsheet', verbose_name="Taqsimot varag'i")),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_records', to='scheduling.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi oylik yuklamasi",
                'verbose_name_plural': "O'qituvchilar oylik yuklamalari",
                'db_table': 'teacher_loads',
            },
        ),
        migrations.CreateModel(
            name='LoadDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(help_text='CurriculumSubject topilmasa ham saqlanadi', max_length=255, verbose_name='Modul nomi (Excel dan)')),
                ('group_name', models.CharField(help_text='Group topilmasa ham saqlanadi', max_length=100, verbose_name='Guruh nomi (Excel dan)')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Soat soni')),
                ('curriculum_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_distributions', to='academic.curriculumsubject', verbose_name="O'quv rejadagi fan")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_distributions', to='academic.group', verbose_name='Guruh')),
                ('teacher_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='scheduling.teacherload', verbose_name="O'qituvchi yuklamasi")),
            ],
            options={
                'verbose_name': 'Taqsimot elementi',
                'verbose_name_plural': 'Taqsimot elementlari',
                'db_table': 'load_distributions',
                'ordering': ['teacher_load', 'module_name', 'group_name'],
            },
        ),
    ]
