# Generated by Django 6.0.2 on 2026-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_loadsheet_teacherload_loaddistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherbusytime',
            name='is_all_day',
            field=models.BooleanField(default=False, help_text="Belgilansa, o'sha kunda hech qanday para qo'yilmaydi", verbose_name='Butun kun band'),
        ),
        migrations.AlterField(
            model_name='teacherbusytime',
            name='end_time',
            field=models.TimeField(blank=True, help_text="is_all_day=False bo'lganda to'ldirish shart", null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='teacherbusytime',
            name='start_time',
            field=models.TimeField(blank=True, help_text="is_all_day=False bo'lganda to'ldirish shart", null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
