# Generated by Django 6.0.2 on 2026-06-03 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_group_day_assignment_building'),
        ('scheduling', '0004_teacher_busy_time_all_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to=settings.AUTH_USER_MODEL)),
                ('curriculum_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='academic.curriculumsubject', verbose_name="O'quv reja fani")),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_subject_assignments', to='scheduling.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Fan o'qituvchisi",
                'verbose_name_plural': "Fan o'qituvchilari",
                'db_table': 'subject_teachers',
            },
        ),
    ]
