# Generated by Django 6.0.2 on 2026-07-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_add_computer_room_type'),
        ('scheduling', '0005_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organizations.department', verbose_name='Kafedra'),
        ),
    ]
