# Generated by Django 6.0.2 on 2026-07-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='is_online',
            field=models.BooleanField(default=False, help_text="Belgilangan bo'lsa — dars Zoom orqali o'tiladi, room/building bo'sh qoladi", verbose_name='Onlayn (Zoom)'),
        ),
    ]
