# Generated by Django 6.0.2 on 2026-08-02 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_subject_teacher_data(apps, schema_editor):
    """
    Eski SubjectTeacher (curriculum_subject'ga OneToOne, guruhga bog'lanmagan) dagi
    har bir yozuvni — shu o'quv reja (Major) ga tegishli BARCHA guruhlar uchun —
    yangi GroupSubject'ga ko'chiradi. Bu faqat boshlang'ich qiymat: avvalgi "hamma
    guruhga bir xil o'qituvchi" holatini saqlab qoladi, shundan keyin har bir guruh
    mustaqil ravishda qayta tahrirlanishi mumkin.
    """
    SubjectTeacher = apps.get_model('scheduling', 'SubjectTeacher')
    GroupSubject   = apps.get_model('scheduling', 'GroupSubject')
    Group          = apps.get_model('academic', 'Group')

    for st in SubjectTeacher.objects.select_related(
        'curriculum_subject__block__curriculum'
    ).all():
        major_id = st.curriculum_subject.block.curriculum.major_id
        if not major_id:
            continue
        for group_id in Group.objects.filter(major_id=major_id).values_list('id', flat=True):
            GroupSubject.objects.get_or_create(
                curriculum_subject_id=st.curriculum_subject_id,
                group_id=group_id,
                defaults={
                    'teacher_id':     st.teacher_id,
                    'assigned_by_id': st.assigned_by_id,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_curriculum_delivery_mode_group_delivery_mode'),
        ('scheduling', '0007_scheduleentry_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_subject_assignments', to=settings.AUTH_USER_MODEL)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='academic.curriculumsubject', verbose_name="O'quv reja fani")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='academic.group', verbose_name='Guruh')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_subject_assignments', to='scheduling.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh fani',
                'verbose_name_plural': 'Guruh fanlari',
                'db_table': 'group_subjects',
                'unique_together': {('curriculum_subject', 'group')},
            },
        ),
        migrations.RunPython(copy_subject_teacher_data, noop_reverse),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
