# Generated by Django 6.0.2 on 2026-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_replace_subjectteacher_with_groupsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubject',
            name='is_vacant',
            field=models.BooleanField(default=False, help_text="Fanga hali o'qituvchi ishga olinmagan — o'rin bo'sh deb belgilangan", verbose_name='Vakant'),
        ),
    ]
