# Generated by Django 6.0.2 on 2026-08-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_groupsubject_is_vacant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — fanga hali o'qituvchi biriktirilmagan/vakant (Vakant)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.teacher', verbose_name="O'qituvchi"),
        ),
    ]
