# Generated by Django 6.0.2 on 2026-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_scheduleentry_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gen_detail',
            field=models.TextField(blank=True, default='', verbose_name='Qadam izohi'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bajarildi (%)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_result',
            field=models.JSONField(blank=True, null=True, verbose_name='Natija (stats/warnings)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_status',
            field=models.CharField(choices=[('idle', 'Boshlanmagan'), ('running', 'Tuzilmoqda'), ('done', 'Tayyor'), ('failed', 'Xatolik')], default='idle', max_length=20, verbose_name='Generatsiya holati'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='gen_step',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Joriy qadam'),
        ),
    ]
