# Generated by Django 6.0.2 on 2026-08-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_position'),
        ('scheduling', '0011_schedule_gen_detail_schedule_gen_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organizations.position', verbose_name='Lavozim'),
        ),
    ]
