# Generated by Django 6.0.2 on 2026-08-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_curriculum_delivery_mode_group_delivery_mode'),
        ('scheduling', '0012_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Nazariy'), ('practice', 'Amaliy')], max_length=20)),
                ('topic', models.TextField(blank=True, default='', verbose_name="O'tilgan mavzu")),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('done', "O'tildi")], default='planned', max_length=10)),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name="To'ldirilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='academic.group', verbose_name='Guruh')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='academic.para', verbose_name='Para')),
                ('schedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='scheduling.scheduleentry', verbose_name='Jadval yozuvi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='academic.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='scheduling.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars jurnali',
                'verbose_name_plural': 'Dars jurnali',
                'db_table': 'lesson_journal',
                'ordering': ['date', 'para__order'],
                'unique_together': {('teacher', 'group', 'subject', 'para', 'date')},
            },
        ),
    ]
