# Generated by Django 6.0.2 on 2026-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_department_options_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', "Ma'ruza zali"), ('lab', 'Laboratoriya'), ('seminar', 'Seminar xonasi'), ('gym', 'Sport zal')], default='lecture', max_length=20),
        ),
    ]
