# Generated by Django 6.0.2 on 2026-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_gym_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', "Ma'ruza zali"), ('lab', 'Laboratoriya'), ('seminar', 'Seminar xonasi'), ('gym', 'Sport zal'), ('computer', 'Kompyuter xonasi')], default='lecture', max_length=20),
        ),
    ]
