# Generated by Django 6.0.2 on 2026-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_add_computer_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_regional',
            field=models.BooleanField(default=False, verbose_name='Viloyatda joylashgan'),
        ),
    ]
