# Generated by Django 6.0.2 on 2026-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'System Super Admin'), ('org_admin', 'Organization Admin'), ('edu_admin', "O'quv Bo'limi Admini"), ('methodist', "O'quv jarayonini metodik ta'minlash bo'limi"), ('dept_manager', 'Kafedra Mudiri'), ('teacher', "O'qituvchi")], default='teacher', max_length=20),
        ),
    ]
