# Generated by Django 6.0.2 on 2026-03-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_department_options_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="O'quv reja nomi")),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semestr')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('archived', 'Arxivlangan')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalar",
                'db_table': 'curriculums',
            },
        ),
        migrations.CreateModel(
            name='CurriculumBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Blok tartibi')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='academic.curriculum')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_blocks', to='organizations.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloklar',
                'db_table': 'curriculum_blocks',
                'ordering': ['order'],
                'unique_together': {('curriculum', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(max_length=50, verbose_name="Yo'nalish kodi")),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='organizations.organization')),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi",
                'verbose_name_plural': "Ta'lim yo'nalishlari",
                'db_table': 'majors',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='Talabalar soni')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], null=True, verbose_name='Oy')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organizations.organization')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academic.major', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
                'unique_together': {('organization', 'name', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='academic.major'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Smena nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Smena',
                'verbose_name_plural': 'Smenalar',
                'db_table': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Fan kodi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'subjects',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Para nomi')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Tartib')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paras', to='academic.shift')),
            ],
            options={
                'verbose_name': 'Para',
                'verbose_name_plural': 'Paralar',
                'db_table': 'paras',
                'ordering': ['order'],
                'unique_together': {('shift', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='organizations.building')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.group')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='academic.shift')),
            ],
            options={
                'verbose_name': 'Guruh biriktiruvi',
                'verbose_name_plural': 'Guruh biriktiruvilari',
                'db_table': 'group_assignments',
                'unique_together': {('group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Nazariy'), ('practice', 'Amaliy')], max_length=20)),
                ('total_hours', models.PositiveSmallIntegerField(help_text='1 para = 2 soat', verbose_name='Jami soat')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.curriculumblock')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'curriculum_subjects',
                'unique_together': {('block', 'subject', 'lesson_type')},
            },
        ),
    ]
