# Generated by Django 6.0.2 on 2026-03-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_subject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='semester',
        ),
    ]
