# Generated by Django 6.0.2 on 2026-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_curriculum_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumsubject',
            options={'ordering': ['order'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('block', 'subject')},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='contingent',
            field=models.CharField(blank=True, help_text="Masalan: Sport ta'lim muassasalarining trenerlari", max_length=255, verbose_name='Tinglovchilar kontingenti'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Kurs muddati (hafta)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='study_form',
            field=models.CharField(choices=[('fulltime', 'Kunduzgi (asosiy ishdan ajralgan holda)'), ('parttime', 'Sirtqi (asosiy ishdan ajralmagan holda)'), ('distance', 'Masofaviy')], default='fulltime', max_length=20, verbose_name="O'qish shakli"),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='total_hours',
            field=models.PositiveSmallIntegerField(default=144, verbose_name='Jami soat'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='field_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ko'chma mashg'ulot soati"),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='independent_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mustaqil tayyorgarlik soati'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='lecture_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nazariy soat'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Blok ichidagi tartib (1.1, 1.2, ...)', verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='practice_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Amaliy soat'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='week1_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='I-hafta soati'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='week2_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='II-hafta soati'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='week3_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='III-hafta soati'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='week4_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='IV-hafta soati'),
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='total_hours',
        ),
    ]
