# Generated by Django 6.0.2 on 2026-04-07 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_curriculumsubject_options_and_more'),
        ('organizations', '0002_alter_department_options_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumblock',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Excel dan yuklaganda bo'sh bo'lishi mumkin, keyinchalik biriktiriladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_blocks', to='organizations.department', verbose_name='Kafedra'),
        ),
    ]
