# Generated by Django 6.0.2 on 2026-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_block_department_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumblock',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Blok nomi'),
        ),
    ]
