# Generated by Django 6.0.2 on 2026-04-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_add_block_name'),
        ('organizations', '0004_add_computer_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumblock',
            name='department',
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Shu fanni qaysi kafedra o'tishi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_subjects', to='organizations.department', verbose_name='Kafedra'),
        ),
    ]
