# Generated by Django 6.0.2 on 2026-06-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_move_department_to_subject'),
        ('organizations', '0004_add_computer_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_assignments', to='academic.group', verbose_name='Guruh')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_assignments', to='organizations.room', verbose_name='Xona')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_assignments', to='academic.shift', verbose_name='Smena')),
            ],
            options={
                'verbose_name': 'Guruh kunlik biriktiruvi',
                'verbose_name_plural': 'Guruh kunlik biriktiruvilari',
                'db_table': 'group_day_assignments',
                'ordering': ['date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
