# Generated by Django 6.0.2 on 2026-06-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_group_day_assignment'),
        ('organizations', '0004_add_computer_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdayassignment',
            name='room',
        ),
        migrations.AddField(
            model_name='groupdayassignment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_assignments', to='organizations.building', verbose_name='Bino'),
        ),
    ]
