# Generated by Django 6.0.2 on 2026-07-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_group_day_assignment_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='requires_computer_room',
            field=models.BooleanField(default=False, help_text="Belgilansa, jadval generatsiyasida bu fan uchun faqat 'Kompyuter xonasi' turidagi xona tanlanadi (IT/AKT fanlari uchun)", verbose_name="Kompyuter xonasida o'tilishi shart"),
        ),
    ]
