# Generated by Django 6.0.2 on 2026-07-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_subject_requires_computer_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
    ]
