# Generated by Django 6.0.2 on 2026-07-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='approved_date',
            field=models.DateField(blank=True, help_text="Shu sanadan boshlab ushbu o'quv reja qo'llaniladi — bir yo'nalishda bir nechta faol o'quv reja bo'lsa, tanlashda shu sana asos bo'ladi", null=True, verbose_name='Tasdiqlangan sana'),
        ),
    ]
