# Generated by Django 6.0.2 on 2026-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_curriculum_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='delivery_mode',
            field=models.CharField(choices=[('offline', 'Oflayn'), ('online', 'Onlayn (Zoom)')], default='offline', help_text="Oflayn yoki onlayn (Zoom) — bir yo'nalishda ikkalasi mustaqil ravishda bir vaqtda mavjud bo'lishi mumkin (masalan bitta oflayn, bitta onlayn faol o'quv reja), har biri o'z tasdiqlangan sanasi bo'yicha almashinadi", max_length=20, verbose_name="O'qitish turi"),
        ),
        migrations.AddField(
            model_name='group',
            name='delivery_mode',
            field=models.CharField(choices=[('offline', 'Oflayn'), ('online', 'Onlayn (Zoom)')], default='offline', help_text="Onlayn guruhlar uchun 'Guruh biriktirish'da faqat smena kerak, bino shart emas — jadval generatsiyasida xona/bino tanlanmaydi (Zoom)", max_length=20, verbose_name="O'qitish turi"),
        ),
    ]
